### ISSUE TITLE
 Failed to lookup symbol 'hid_enumerate': dlsym(RTLD_DEFAULT, hid_enumerate): symbol not found

### ISSUE THREAD

**Issue by MaxSKuzin** [rustui/hid#10]
Trying to get device list on MacOS and facing this issue.

**Comment by jgop** [comment]
I have the same issue in MacOS...

**Comment by MaxSKuzin** [comment]
> I have the same issue in MacOS...

Found solution. You need to copy hid.c for MacOS from https://github.com/libusb/hidapi#installing-hidapi and all files which it depends on

**Comment by jgop** [comment]
Hello, thanks for the help. But i Copy the files and paste were? I am new in flutter...

**Comment by MaxSKuzin** [comment]
> Hello, thanks for the help. But i Copy the files and paste were? I am new in flutter...

Paste them in macos/runner. After that add them with xcode
