### ISSUE TITLE
Send APDU

### ISSUE THREAD

**Issue by redDwarf03** [rustui/hid#5]
hello
is it possible with your project to send APDU like in this project https://github.com/LedgerHQ/ledgercomm ?
Thank you

**Comment by rustui** [comment]
I don't know much about APDU.
After exploring the link you posted a bit, I think it might be possible, but you must connect devices via USB and construct raw bytes by hand.

**Comment by redDwarf03** [comment]
ok. thanks
your library provides a async API. could you provide a non-async API please ?

**Comment by rustui** [comment]
Android and web platforms does not support sync api. There is also no way to convert an async api to a sync one in dart.

**Comment by redDwarf03** [comment]
Ok thx for your answer
